<?php

namespace App\Repositories\Contracts;

use App\Enums\PostSort;
use App\Models\Post;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/**
 * Every returned post carries its author, group and the aggregates
 * upvotes_count, downvotes_count and comments_count. Deleted posts are never returned.
 *
 * $viewerId, where accepted, adds that user's own vote as `viewer_vote` (true/false/null);
 * omitted or null (a guest) leaves it unset.
 */
interface PostRepositoryInterface
{
    /**
     * Plain lookup by id, without the author/group/aggregate loading findWithStatsBySlug() does.
     * Used where the post itself is needed (e.g. authorization checks), not its display data.
     */
    public function find(string $id): ?Post;

    /**
     * By the post's slug, which is unique within its group (used in page URLs).
     */
    public function findWithStatsBySlug(string $groupId, string $slug, ?string $viewerId = null): ?Post;

    public function paginateForGroup(string $groupId, PostSort $sort, int $perPage, ?string $viewerId = null): LengthAwarePaginator;

    /**
     * Posts from public groups created within the last $days days, best score first.
     */
    public function paginateTrending(int $days, int $perPage, ?string $viewerId = null): LengthAwarePaginator;

    /**
     * Posts from every group the user is subscribed to, newest first.
     */
    public function paginateForSubscriber(string $userId, int $perPage): LengthAwarePaginator;

    /**
     * The author's posts, newest first, for their profile page. Posts in a private group are
     * included only when the viewer is a member of that group; a guest sees public groups only.
     */
    public function paginateForAuthor(string $authorId, int $perPage, ?string $viewerId = null): LengthAwarePaginator;

    /**
     * Persists a new post. $slug is expected to already be generated by the caller (PostService).
     */
    public function create(string $groupId, string $userId, ?string $title, string $article, string $slug): Post;

    /**
     * A random, non-deleted post's slug from the group, or null when it has none. For "I'm feeling lucky".
     */
    public function randomSlugForGroup(string $groupId): ?string;
}
