<?php

namespace App\Repositories\Contracts;

use App\Enums\PostSort;
use App\Models\Post;
use App\Support\FeedFilters;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/**
 * Every returned post carries its author, group and the aggregates
 * upvotes_count, downvotes_count, comments_count and shares_count. Deleted posts are never returned.
 *
 * $viewerId, where accepted, adds that user's own vote as `viewer_vote` (true/false/null);
 * omitted or null (a guest) leaves it unset.
 */
interface PostRepositoryInterface
{
    /**
     * Plain lookup by id, without the author/group/aggregate loading findWithStatsBySlug() does.
     * Used where the post itself is needed (e.g. authorization checks), not its display data.
     */
    public function find(string $id): ?Post;

    /**
     * By the post's slug, which is unique within its group (used in page URLs).
     */
    public function findWithStatsBySlug(string $groupId, string $slug, ?string $viewerId = null): ?Post;

    public function paginateForGroup(string $groupId, PostSort $sort, int $perPage, ?string $viewerId = null): LengthAwarePaginator;

    /**
     * Posts from public groups, freshest bucket first, best score first within a bucket.
     * $freshnessDays are ascending bucket bounds: [7, 30] = this week, this month, older.
     *
     * $maxAgeDays, when given, drops older posts (the period filter).
     *
     * @param  list<int>  $freshnessDays
     */
    public function paginateTrending(array $freshnessDays, int $perPage, ?string $viewerId = null, ?int $maxAgeDays = null): LengthAwarePaginator;

    /**
     * Trending, made personal for one user: never their own posts or groups they're already in
     * (those are in Following), and posts in groups of a language they speak come first —
     * a priority, not a filter, so the list isn't empty while there are few posts. Then by
     * freshness bucket and score, as in paginateTrending(). $filters narrow it further: only
     * unseen posts, only their languages (strict), a period.
     *
     * @param  list<int>  $freshnessDays
     */
    public function paginateRecommended(string $userId, array $freshnessDays, int $perPage, FeedFilters $filters = new FeedFilters): LengthAwarePaginator;

    /**
     * Posts from every group the user is subscribed to, newest first, narrowed by $filters.
     */
    public function paginateForSubscriber(string $userId, int $perPage, FeedFilters $filters = new FeedFilters): LengthAwarePaginator;

    /**
     * The author's posts, newest first, for their profile page. Posts in a private group are
     * included only when the viewer is a member of that group; a guest sees public groups only.
     */
    public function paginateForAuthor(string $authorId, int $perPage, ?string $viewerId = null): LengthAwarePaginator;

    /**
     * Posts by every author the user follows, newest first, with the same private-group rule as
     * paginateForAuthor() (the follower is the viewer), narrowed by $filters.
     */
    public function paginateForFollower(string $followerId, int $perPage, FeedFilters $filters = new FeedFilters): LengthAwarePaginator;

    /**
     * Persists a new post. $slug is expected to already be generated by the caller (PostService).
     */
    public function create(string $groupId, string $userId, ?string $title, string $article, string $slug): Post;

    /**
     * Notes that the user opened the post. Idempotent: the first view is kept.
     */
    public function recordView(string $postId, string $userId): void;

    /**
     * Notes that the user shared the post. Idempotent, so each user counts once.
     */
    public function recordShare(string $postId, string $userId): void;

    public function sharesCount(string $postId): int;

    /**
     * A random, non-deleted post's slug from the group, or null when it has none. For "I'm feeling lucky".
     */
    public function randomSlugForGroup(string $groupId): ?string;
}
